(in-package :matlisp)

(defun graph->dot (stream g &optional self-loops node-name)
  (if (null stream)
      (with-output-to-string (out) (graph->dot out g))
      (progn; ((nei (neighbours graph)))
	(format stream "digraph G{~%graph [];~%node[shape=point];~%~%")
	(iter (for u from 0 below (dimensions g -1)) (format stream "~a [xlabel=\"~a\"];~%" u (if node-name (aref node-name u) "")))
	(iter (for u from 0 below (dimensions g -1))
	      (letv* ((lb ub (fence g u)))
		(iter (for v in-vector (δ-i g) from lb below ub)
		      (when (or (and (= u v) (not self-loops)) (and (< v u) (δ-i g v u))) (next-iteration))
		      (format stream (string+ "~a->~a [" (if (δ-i g v u) "dir=none,color=red," "")  "label=\"\",];~%") v u))))
	(format stream "}~%"))))

(defun display-graph (graph &optional self-loops node-name)
  (with-open-file (out "/tmp/matlisp-tmp.out" :direction :output :if-exists :supersede :if-does-not-exist :create)
    (graph->dot out graph self-loops node-name))
  (with-open-file (out "/tmp/matlisp-tmp.svg" :direction :output :if-exists :supersede :if-does-not-exist :create)
    (external-program:run "/usr/bin/neato" (list "/tmp/matlisp-tmp.out" "-Tsvg") :output out))
  (external-program:run "/usr/bin/inkview" (list "/tmp/matlisp-tmp.svg") :output nil :wait nil))
